// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Args = { name: string, };

export type Channel = "greet";

export type Response = { message: string, };
