// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GreetArgs = { name: string, };

export type GreetChannelName = "greet";

export type GreetResponse = { message: string, };
