// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Args = { requestId: string, };

export type Channel = "random_example";

export type Error = { errorMessage: string, };

export type Response = { message: string, responseId: string, timestamp: string, };
