// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RandomExampleArgs = { requestId: string, };

export type RandomExampleChannelName = "random_example";

export type RandomExampleError = { errorMessage: string, };

export type RandomExampleResponse = { message: string, responseId: string, timestamp: string, };
